name: pages-build-and-deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Add build steps if necessary
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build
      #   run: npm run build

      # Trigger the GitHub Pages deployment action
      - name: Trigger Pages Build Deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Uploads the current directory as an artifact
