name: pages-build-and-deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write    # <-- Add this line
  id-token: write

jobs:
  deploy-to-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Upload files for deployment
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3  # <-- Updated to v3
        with:
          path: .  # Include all files in the root directory (index.html, lp_data.json, etc.)

      # 3. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
