name: pages-build-and-deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # If you have any build steps (npm run build, etc.), add them here.
      # Otherwise, do nothing -- the index.html is already in the root.
      #
      # - name: Install dependencies
      #   run: npm ci
      #
      # - name: Build
      #   run: npm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # 1) Upload everything in the repo root (including index.html)
      #    to the Pages artifact. If you only want certain files/folders,
      #    adjust the path: below accordingly.
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Use '.' so it uploads the current directory (index.html in root)

  # GitHub automatically adds the "pages-build-deployment" or "report-build-status" 
  # job after these steps, which deploys the artifact to your GitHub Pages.
